export const ROUTES = {
    HOME: "/",
    CART: "/cart",
    FAVOURITES: "/favourites",
    CATEGORY: "/categories/:id",
    PRODUCTS: "/products/:id",
    LOGIN: "/login",
    SIGNUP: "/signUp",
    CATEGORIESADM: "adm/categories/all",
    TYPESADM: "adm/types/",
    USERSADM: "adm/users/all",
    TYPEONLYADM: "adm/types/:id",
    ORDER: "/order",
    PROFILE: "/profile",
}